module.exports = {
  BROADCAST_DISCONNECT: "BROADCAST_DISCONNECT",
  BROADCAST_SEND_MESSAGE: "BROADCAST_SEND_MESSAGE",
  BROADCAST_JOIN_ROOM: "BROADCAST_JOIN_ROOM",
  BROADCAST_NEW_CALL: "RTC_BROADCAST_NEW_CALL",
  BROADCAST_CALL: "RTC_BROADCAST_CALL",
  BROADCAST_END_CALL: "RTC_BROADCAST_END_CALL",

  SEND_MESSAGE: "SEND_MESSAGE",
  NEW_MESSAGE: "NEW_MESSAGE",
  USER_CONNECTED: "USER_CONNECTED",
  JOIN_ROOM: "JOIN_ROOM",
  USER_CONNECTED: "USER_CONNECTED",
  DISCONNECT: "DISCONNECT",
  CHECK_ROOM: "CHECK_ROOM",
  CREATE_ROOM: "CREATE_ROOM",
  ERROR: "CUSTOM_ERROR",
  CALL: "RTC_CALL",
  CALL_REQUEST: "RTC_CALL_REQUEST",
  END_CALL: "RTC_END_CALL"
};